# Generated by Django 5.2.15 on 2026-09-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The migration that creates `identity.Package`, not the latest one the
        # autodetector happened to see. A dependency on a later migration makes this
        # one un-appliable in any ordering that does not include it, for no reason a
        # reader could work out from the models.
        ('identity', '0001_package_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_key', models.CharField(max_length=128, verbose_name='finding key')),
                ('finding_facts', models.CharField(blank=True, default='', max_length=1024, verbose_name='finding facts')),
                ('queue', models.CharField(choices=[('identity_review', 'identity review'), ('remediation', 'remediation'), ('compliance_review', 'compliance review')], max_length=17, verbose_name='queue')),
                ('state', models.CharField(choices=[('open', 'open'), ('triaged', 'triaged'), ('routed', 'routed'), ('in_progress', 'in progress'), ('resolved', 'resolved'), ('accepted', 'accepted')], default='open', max_length=11, verbose_name='state')),
                ('opened_at', models.DateTimeField(verbose_name='opened at')),
                ('changed_at', models.DateTimeField(verbose_name='changed at')),
                ('claimed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_workflow_items', to=settings.AUTH_USER_MODEL, verbose_name='claimed by')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_items', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'workflow item',
                'verbose_name_plural': 'workflow items',
                'db_table': 'workflow_items',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('open', 'open'), ('triaged', 'triaged'), ('routed', 'routed'), ('in_progress', 'in progress'), ('resolved', 'resolved'), ('accepted', 'accepted')], max_length=11, verbose_name='from state')),
                ('to_state', models.CharField(choices=[('open', 'open'), ('triaged', 'triaged'), ('routed', 'routed'), ('in_progress', 'in progress'), ('resolved', 'resolved'), ('accepted', 'accepted')], max_length=11, verbose_name='to state')),
                ('queue', models.CharField(choices=[('identity_review', 'identity review'), ('remediation', 'remediation'), ('compliance_review', 'compliance review')], max_length=17, verbose_name='queue')),
                ('justification', models.CharField(blank=True, default='', max_length=2000, verbose_name='justification')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_transitions', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='workflow.workflowitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'workflow transition',
                'verbose_name_plural': 'workflow transitions',
                'db_table': 'workflow_transitions',
            },
        ),
        migrations.AddIndex(
            model_name='workflowitem',
            index=models.Index(fields=['queue', 'state'], name='workflow_queue_state'),
        ),
        migrations.AddIndex(
            model_name='workflowitem',
            index=models.Index(fields=['package', 'state'], name='workflow_package_state'),
        ),
        migrations.AddConstraint(
            model_name='workflowitem',
            constraint=models.UniqueConstraint(fields=('finding_key',), name='workflow_one_item_per_finding_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claimed_by__isnull', False), ('state', 'in_progress')), models.Q(models.Q(('state', 'in_progress'), _negated=True), ('claimed_by__isnull', True)), _connector='OR'), name='workflow_claimed_only_while_in_progress'),
        ),
        migrations.AddIndex(
            model_name='workflowtransition',
            index=models.Index(fields=['item', 'occurred_at'], name='workflow_item_occurred'),
        ),
    ]
