# The queue labels, which `CPM-APP-S15` rewrote from lower case to sentence case.
#
# **No column changes and no data moves.** `choices` is validation and display
# metadata that Django keeps in the migration state; the stored values --
# `identity_review`, `remediation`, `compliance_review` -- are untouched, and so is
# every row. Django generates an `AlterField` for a `choices` change regardless, and
# `tests/unit/django_apps/test_migration_completeness.py` is what insists it be
# written down rather than left as a silent divergence between the models and the
# graph.
#
# Why the labels changed: every surface rendered the queue's stored *value*, so a
# reviewer's navigation read `identity_review`. The labels existed on `Queue` from
# `CPM-APP-S04` and nothing had ever used them -- which is also why they were lower
# case, since nothing was reading them to notice.

# Generated by Django 5.2.15 on 2026-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_workflow_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowitem',
            name='queue',
            field=models.CharField(choices=[('identity_review', 'Identity review'), ('remediation', 'Remediation'), ('compliance_review', 'Compliance review')], max_length=17, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='queue',
            field=models.CharField(choices=[('identity_review', 'Identity review'), ('remediation', 'Remediation'), ('compliance_review', 'Compliance review')], max_length=17, verbose_name='queue'),
        ),
    ]
