# Generated by Django 5.2.15 on 2026-09-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source_package_key', models.CharField(max_length=512, verbose_name='source package key')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('internal_component_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='internal component count')),
                ('internal_lob_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='internal LOB count')),
                ('apps', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='apps')),
                ('platforms', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='platforms')),
                ('downloads', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='downloads')),
                ('versions', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='versions')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'inventory snapshot',
                'verbose_name_plural': 'inventory snapshots',
                'db_table': 'inventory_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='inv_snapshot_pkg_observed'), models.Index(fields=['source_package_key'], name='inv_snapshot_source_key')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('internal_component_count__isnull', False), ('internal_lob_count__isnull', False), ('state', 'ok')), models.Q(models.Q(('state', 'ok'), _negated=True), ('internal_component_count__isnull', True), ('internal_lob_count__isnull', True)), _connector='OR'), name='inventory_counts_present_exactly_when_observed')],
            },
        ),
    ]
