# Generated by Django 5.2.15 on 2026-09-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=128, unique=True, verbose_name='canonical name')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='display name')),
                ('source_repository_url', models.URLField(blank=True, default='', max_length=512, verbose_name='source repository URL')),
                ('primary_purl', models.CharField(blank=True, default='', max_length=512, verbose_name='primary purl')),
                ('primary_type', models.CharField(blank=True, default='', max_length=128, verbose_name='primary type')),
                ('conda_purl', models.CharField(blank=True, default='', max_length=512, verbose_name='conda purl')),
                ('alternative_purls', models.JSONField(blank=True, default=list, verbose_name='alternative purls')),
                ('cpes', models.JSONField(blank=True, default=list, verbose_name='CPEs')),
                ('identity_source', models.CharField(blank=True, default='', max_length=128, verbose_name='identity source')),
                ('associator_key', models.CharField(blank=True, default='', max_length=512, verbose_name='associator key')),
                ('resolved_at', models.DateTimeField(verbose_name='resolved at')),
                ('confidence', models.CharField(choices=[('verified', 'Verified'), ('inventory-derived', 'Inventory Derived'), ('unmapped', 'Unmapped')], default='unmapped', max_length=32, verbose_name='confidence')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'db_table': 'packages',
                'constraints': [models.CheckConstraint(condition=models.Q(('canonical_name', ''), _negated=True), name='canonical_name_is_present')],
            },
        ),
        migrations.CreateModel(
            name='Feedstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('url', models.URLField(blank=True, default='', max_length=512, verbose_name='URL')),
                ('metadata_url', models.URLField(blank=True, default='', max_length=512, verbose_name='metadata URL')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedstocks', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'feedstock',
                'verbose_name_plural': 'feedstocks',
                'db_table': 'feedstocks',
                'constraints': [models.UniqueConstraint(fields=('package', 'name'), name='one_feedstock_name_per_package'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='feedstock_name_is_present')],
            },
        ),
    ]
