# Generated by Django 5.2.15 on 2026-09-05 16:52
#
# Hand-edited once, to add `check_source_keys_are_unique` in front of the
# `one_package_per_source_key` constraint. `AddConstraint` alone fails on a
# database that already holds a duplicate non-blank pair -- with the backend's
# own message, naming an index nobody has heard of, after `package_mappings` has
# already been created -- and a database written before CPM-IDENTITY-S02 is
# exactly where those duplicates are, because the constraint is what this story
# added to stop them accruing. The check turns that into a message naming the
# pairs and what to do about them.

import django.db.models.deletion
from django.db import migrations, models


def duplicate_source_keys(package_model):
    """Return every non-blank (identity_source, associator_key) pair held twice.

    Blank keys are excluded because the constraint excludes them: a package no
    source claims is deliberately not constrained, so two of them are not a
    duplicate.
    """
    return [
        (row["identity_source"], row["associator_key"])
        for row in package_model.objects.exclude(associator_key="")
        .values("identity_source", "associator_key")
        .annotate(rows=models.Count("id"))
        .filter(rows__gt=1)
    ]


def refuse_duplicate_source_keys(duplicates):
    """Raise when any pair is held twice, naming the pairs.

    Separate from the query so the refusal is reachable from a test without a
    database holding rows the new constraint makes impossible to insert.
    """
    if not duplicates:
        return
    listed = ", ".join(f"{source!r}/{key!r}" for source, key in sorted(duplicates))
    message = (
        f"one_package_per_source_key cannot be applied: these (identity_source, associator_key) pairs are "
        f"held by more than one package -- {listed}. They are the duplicate shells CPM-IDENTITY-S06's review "
        f"recorded, created before resolution kept the pair stable. Merge each set onto one row, moving its "
        f"evidence with it, and run this migration again."
    )
    raise RuntimeError(message)


def check_source_keys_are_unique(apps, schema_editor):
    """Refuse to add the constraint to a database that would violate it."""
    refuse_duplicate_source_keys(duplicate_source_keys(apps.get_model("identity", "Package")))


def nothing_to_check(apps, schema_editor):
    """Reversing drops the constraint, so there is nothing to verify on the way back."""


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source_repository', 'Source Repository'), ('release_ecosystem', 'Release Ecosystem'), ('conda_artifact', 'Conda Artifact'), ('feedstock', 'Feedstock'), ('cross_ecosystem', 'Cross Ecosystem')], max_length=32, verbose_name='kind')),
                ('outcome', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('established', 'Established')], default='unknown', max_length=32, verbose_name='outcome')),
                ('resolved_at', models.DateTimeField(verbose_name='resolved at')),
            ],
            options={
                'verbose_name': 'package mapping',
                'verbose_name_plural': 'package mappings',
                'db_table': 'package_mappings',
            },
        ),
        migrations.RunPython(check_source_keys_are_unique, nothing_to_check),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(('associator_key', ''), _negated=True), fields=('identity_source', 'associator_key'), name='one_package_per_source_key'),
        ),
        migrations.AddField(
            model_name='packagemapping',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='identity.package', verbose_name='package'),
        ),
        migrations.AddConstraint(
            model_name='packagemapping',
            constraint=models.UniqueConstraint(fields=('package', 'kind'), name='one_outcome_per_package_mapping'),
        ),
    ]
