# Generated by Django 5.2.15 on 2026-09-05 20:55
#
# Renamed from the generated `0003_identityoverride` so the file says which table
# it creates in the spelling the rest of this repository uses; nothing else is
# hand-edited.
#
# `identity_overrides` is the audit row CPM-AD-14 requires of the product's one
# governed human write, and CPM-FR-32 makes it append-only and independently
# queryable. The append-only half is the model's, not this migration's: the table
# it builds is an ordinary one, and `core.models.AppendOnlyModel` is what refuses
# a re-save, an `update()` and a `delete()` against it.
#
# The custom permission in `options` is the other half of the story. Creating the
# `auth_permission` row for it is `post_migrate`'s work and attaching it to the
# leadership role group is `core/0005_grant_identity_override.py`'s, which depends
# on this migration and calls `create_permissions` first for exactly that reason.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('prior_canonical_name', models.CharField(max_length=128, verbose_name='prior canonical name')),
                ('new_canonical_name', models.CharField(max_length=128, verbose_name='new canonical name')),
                ('prior_display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='prior display name')),
                ('new_display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='new display name')),
                ('prior_confidence', models.CharField(choices=[('verified', 'Verified'), ('inventory-derived', 'Inventory Derived'), ('unmapped', 'Unmapped')], max_length=32, verbose_name='prior confidence')),
                ('new_confidence', models.CharField(choices=[('verified', 'Verified'), ('inventory-derived', 'Inventory Derived'), ('unmapped', 'Unmapped')], max_length=32, verbose_name='new confidence')),
                ('reason', models.TextField(verbose_name='reason')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_overrides', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_overrides', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'identity override',
                'verbose_name_plural': 'identity overrides',
                'db_table': 'identity_overrides',
                'ordering': ('-observed_at', '-id'),
                'permissions': [('override_package_identity', 'Can override a package identity')],
                'indexes': [models.Index(fields=['package', '-observed_at'], name='identity_ovr_pkg_observed')],
            },
        ),
    ]
