# Generated by Django 5.2.15 on 2026-09-06 20:37
#
# `version_authority_order`, CPM-AD-6's "the authority order is data on the
# package" (CPM-CURRENCY-S06). A JSON list column on the terms `alternative_purls`
# and `cpes` are declared: NOT NULL with a `list` default, so "no preference
# recorded" is `[]` and never NULL.
#
# Unedited, and there is no data step: every existing package acquires `[]`,
# which is exactly what "no authority is explicitly set" means and is the value
# `identity.applied_authority_order` applies `DEFAULT_AUTHORITY_ORDER` for.
# Backfilling the default into the column would have made AC 2 unfalsifiable --
# there would be no stored value for a recorded order to differ from.
#
# The `validators` entry is a reference to a function in `identity/models.py`
# rather than a copy of the rule, which is what a validator deconstructs to. It
# runs from `full_clean()` and not from `save()`; the refusal a policy run meets
# is `policies/currency.py`'s read of the same rule.

import conda_package_supply_chain_monitor.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_identity_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='version_authority_order',
            field=models.JSONField(blank=True, default=list, validators=[conda_package_supply_chain_monitor.identity.models.validate_authority_order], verbose_name='version authority order'),
        ),
    ]
