"""The collector declarations refuse a *real* boot, proved in a real process.

`CPM-AD-20` and `CPM-AD-28` both say a component whose collectors are misdeclared
refuses to start. `config/startup/stage_two.py` evaluates both as conditions 10
and 11 -- and in a deployed process it evaluates them over an **empty registry**,
because stage two runs from `django_service.users`' `ready()` and
`tests/unit/startup/test_installed_apps_ordering.py` requires every adopted
application to be installed after that owner. Every other case about those two
rules runs after `django.setup()` has finished, so every one of them meets a
populated registry and none of them notices.

So this module boots a child process. `CollectorsConfig.ready()` calls the same
two public rules immediately after it registers the collectors, and what is
asserted here is that a deliberately misdeclared component **does not start** --
which is the only claim `pixi run ci` can make about a deployment, and the claim
six shipped artefacts were making before this module existed.

**The child is a real `django.setup()` and nothing less.** A case that called
`ready()` by hand would prove that the function raises, which is not in doubt; it
would not prove that anything calls it before a worker picks up work. The setup
is what an entrypoint, a management command and a gunicorn master all perform,
so a refusal out of it is a refusal of the process.

**A generated settings module rather than `override_settings`.** The refusal
fires during `django.setup()`, before any test could patch anything, so the
schedule has to be wrong in the settings module the child imports. It is composed
from `config.settings.local` for the reason
`tests/integration/startup/test_stage_two_served_path.py` gives: it is the only
fully populated module a test can reach without real deployment secrets.

`tests/integration/conftest.py` marks everything under `tests/integration/` as an
integration test; the marker is not re-applied by hand.
"""

from __future__ import annotations

import json
import subprocess
import sys
from typing import TYPE_CHECKING
from typing import Final

from conda_package_supply_chain_monitor.collectors.pypi_release import COLLECTOR_NAME as PYPI_RELEASE_NAME
from conda_package_supply_chain_monitor.collectors.pypi_release import PYPI_RELEASE_CADENCE
from conda_package_supply_chain_monitor.collectors.sweep import COLLECTOR_KWARG
from conda_package_supply_chain_monitor.collectors.sweep import SWEEP_TASK_NAME
from config.locality import LOCAL
from config.locality import PROCESS_ENV_VAR
from config.locality import RUNTIME_ENV_VAR
from tests.conftest import subprocess_env

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

#: How long a child gets to import settings, run `django.setup()` and write its
#: report. Generous, because it is a cold interpreter importing Django and this
#: whole application; a ceiling at all is what turns a hang into a failure.
BOOT_TIMEOUT_SECONDS: Final[float] = 120.0

#: The mismatched interval one case declares: seven times the collector's own
#: cadence, which is exactly the weekly-against-daily disagreement
#: `CPM-CURRENCY-S01` recorded as the failure this refusal exists to prevent.
A_MISMATCHED_INTERVAL_DAYS: Final[int] = PYPI_RELEASE_CADENCE.days * 7

#: A collector name nothing in this repository registers, for the backward
#: direction: an entry naming it fires into nothing on every tick.
AN_UNREGISTERED_COLLECTOR: Final[str] = "cpm-boot-probe-renamed"

#: The settings module every child imports, composed from `local` and then
#: amended by exactly one case's fault.
_PROBE_SETTINGS_TEMPLATE: Final = '''\
"""A component's settings, carrying at most one misdeclared collector.

Generated by tests/integration/startup/test_collector_boot_refusal.py.
"""

from datetime import timedelta

from config.settings.local import *  # noqa: F401, F403

DATABASES = {{
    "default": {{
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": {database!r},
    }},
}}

{fault}
'''

#: The faults, keyed by the name each case asks for. `NO_FAULT` is the positive
#: control, and it is the one that would fail if this refusal were over-eager:
#: a component whose schedule and collectors agree must start.
NO_FAULT: Final[str] = "none"
_FAULTS: Final[dict[str, str]] = {
    NO_FAULT: "# The shipped schedule, unamended.",
    "mismatched-cadence": (
        "CELERY_BEAT_SCHEDULE = dict(CELERY_BEAT_SCHEDULE)  # noqa: F405\n"
        f"CELERY_BEAT_SCHEDULE['cpm-sweep-{PYPI_RELEASE_NAME.replace('_', '-')}'] = {{\n"
        f"    'task': {SWEEP_TASK_NAME!r},\n"
        f"    'schedule': timedelta(days={A_MISMATCHED_INTERVAL_DAYS}),\n"
        f"    'kwargs': {{{COLLECTOR_KWARG!r}: {PYPI_RELEASE_NAME!r}}},\n"
        "}\n"
    ),
    "entry-for-nobody": (
        "CELERY_BEAT_SCHEDULE = dict(CELERY_BEAT_SCHEDULE)  # noqa: F405\n"
        "CELERY_BEAT_SCHEDULE['cpm-sweep-renamed'] = {\n"
        f"    'task': {SWEEP_TASK_NAME!r},\n"
        "    'schedule': timedelta(days=1),\n"
        f"    'kwargs': {{{COLLECTOR_KWARG!r}: {AN_UNREGISTERED_COLLECTOR!r}}},\n"
        "}\n"
    ),
}

#: The child. It performs the one thing an entrypoint, a management command and a
#: gunicorn master all perform, and reports what came out of it.
#:
#: A string on purpose: nothing here executes in the test process, so the
#: `print`-free file handoff needs no ruff exemptions.
_BOOT_PROBE_SOURCE: Final = '''
"""Run django.setup() in a component and report whether it refused."""

import json
import sys
from pathlib import Path

import django
from django.core.exceptions import ImproperlyConfigured

REPORT = Path(sys.argv[1])

report = {"refusal": None, "refusal_type": None}
try:
    django.setup()
except ImproperlyConfigured as refusal:
    report["refusal"] = str(refusal)
    report["refusal_type"] = type(refusal).__name__

REPORT.write_text(json.dumps(report), encoding="utf-8")
'''


def _booted(tmp_path: Path, *, fault: str) -> Mapping[str, object]:
    """Boot a child component carrying one fault and report what it met.

    Args:
        tmp_path: The directory the generated settings module, the report and the
            scratch database live in, and the only entry on the child's path.
        fault: Which fault to build into the settings module.

    Returns:
        The child's report: the refusal it met, if any, and its type.

    """
    (tmp_path / "probe_settings.py").write_text(
        _PROBE_SETTINGS_TEMPLATE.format(database=str(tmp_path / "probe.sqlite3"), fault=_FAULTS[fault]),
        encoding="utf-8",
    )
    report_path = tmp_path / "boot.json"

    env = subprocess_env()
    # Local, for the reason `test_stage_two_served_path.py` records: stage 1's
    # FR-12 escape route refuses `config.settings.local` in a deployed run, and
    # this module is not about that refusal. What is under test here is
    # unconditional -- a misdeclared collector is a misconfiguration in any
    # locality -- so a local child is the narrower and the more honest one.
    env[RUNTIME_ENV_VAR] = LOCAL
    env.pop(PROCESS_ENV_VAR, None)
    env["DJANGO_SETTINGS_MODULE"] = "probe_settings"
    # The child's own working directory is the import root for its generated
    # module, so `PYTHONSAFEPATH` -- which is what keeps the interpreter from
    # prepending it -- has to go for this probe.
    env.pop("PYTHONSAFEPATH", None)

    completed = subprocess.run(  # noqa: S603
        [sys.executable, "-c", _BOOT_PROBE_SOURCE, str(report_path)],
        cwd=tmp_path,
        env=env,
        capture_output=True,
        text=True,
        timeout=BOOT_TIMEOUT_SECONDS,
        check=False,
    )

    assert completed.returncode == 0, (
        f"the boot probe exited {completed.returncode}\n"
        f"--- stdout ---\n{completed.stdout}\n--- stderr ---\n{completed.stderr}"
    )
    return json.loads(report_path.read_text(encoding="utf-8"))


def test_a_component_whose_collectors_and_schedule_agree_starts(tmp_path: Path) -> None:
    """The positive control, and the one this repository ships.

    Without it every refusal below would be satisfied by a check that refused
    everything -- which would stop every process in this repository while looking
    exactly like a working guard.
    """
    report = _booted(tmp_path, fault=NO_FAULT)

    assert report["refusal"] is None, f"an unamended component refused to start: {report['refusal']}"


def test_a_component_whose_schedule_contradicts_a_cadence_does_not_start(tmp_path: Path) -> None:
    """`CPM-AD-20`, asserted where it is claimed: a real `django.setup()`.

    Seven times the declared cadence is the weekly-against-daily disagreement
    `CPM-CURRENCY-S01` recorded -- it would make the whole inventory read stale
    six days out of seven, with every collection succeeding and every gate green.
    The message names both numbers, because an operator told only that "the
    cadence does not match" has to go and find out which two things disagreed.

    This is the case that could not exist before `CollectorsConfig.ready()`
    enforced the rule: stage two evaluates it over a registry that this
    application's own `ready()` has not populated yet, so a child booted with this
    exact fault started cleanly.
    """
    report = _booted(tmp_path, fault="mismatched-cadence")

    refusal = str(report["refusal"])
    assert report["refusal"] is not None, "a component whose schedule contradicts a cadence started"
    assert report["refusal_type"] == "ImproperlyConfigured"
    assert PYPI_RELEASE_NAME in refusal
    assert repr(PYPI_RELEASE_CADENCE) in refusal
    assert "days=7" in refusal


def test_a_component_whose_schedule_names_an_unregistered_collector_does_not_start(tmp_path: Path) -> None:
    """The backward direction, in the same real process.

    A renamed collector leaves a beat entry firing into nothing, on every tick,
    and the surface it was meant to observe goes quietly unobserved.
    """
    report = _booted(tmp_path, fault="entry-for-nobody")

    assert report["refusal"] is not None, "a component with an entry for no collector started"
    assert report["refusal_type"] == "ImproperlyConfigured"
    assert AN_UNREGISTERED_COLLECTOR in str(report["refusal"])
