# Generated by Django 5.2.15 on 2026-09-06 22:08
#
# `package_currency`, the derived table CPM-CURRENCY-S06's currency pass owns:
# one row per package per policy run, keyed (package, policy_run) exactly as
# CPM-AD-21 requires. The first per-domain policy table in this product; there is
# no data step, because the table starts empty and a policy run fills it.
#
# Regenerated once, in the same story, after review: the `detail` column and the
# three `editable=False` declarations on the authority columns arrived before
# this migration had been applied anywhere, so they belong in the CreateModel
# rather than in a second migration altering a table nobody has ever built.
#
# Hand-edited once, and only the dependencies. The autodetector names each app's
# *newest* migration, which here named `core.0006` and `identity.0004` -- two
# migrations this one does not need. What it actually references is
# `core.PolicyRun` (created by `0002_run_ledger`), `identity.Package` (created by
# `0001_package_identity`) and the four snapshot tables, the last of which
# `collectors.0005` creates. Depending on later migrations would order this one
# behind work it has nothing to do with, which is the same correction
# `collectors.0002` through `0005` each carry.
#
# Otherwise unedited: the model declares the whole of it -- the six status
# columns over the composed CurrencyOutcome vocabulary (CPM-AD-5), every relation
# PROTECT, and the three constraints. The unique constraint is CPM-AD-21's key as
# a database rule; the other two are the row's own invariants, that the named
# authority is a surface this product observes and that a determinate verdict
# names the authority it was reached against. The second of those is built by
# walking `SURFACE_STATUS_FIELDS` in the model and is frozen here as the four
# columns it produced, which is what a migration is for.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0005_conda_package_snapshots'),
        ('core', '0002_run_ledger'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_status', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], editable=False, max_length=32, verbose_name='source currency')),
                ('pypi_status', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], editable=False, max_length=32, verbose_name='PyPI currency')),
                ('feedstock_status', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], editable=False, max_length=32, verbose_name='feedstock currency')),
                ('conda_package_status', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], editable=False, max_length=32, verbose_name='published conda package currency')),
                ('overall_status', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], editable=False, max_length=32, verbose_name='currency')),
                ('detail', models.TextField(blank=True, default='', editable=False, verbose_name='detail')),
                ('chosen_authority', models.CharField(blank=True, choices=[('source', 'Source'), ('pypi', 'Pypi'), ('feedstock', 'Feedstock'), ('conda_package', 'Conda Package')], default='', editable=False, max_length=32, verbose_name='chosen authority')),
                ('authority_order', models.JSONField(blank=True, default=list, editable=False, verbose_name='authority order')),
                ('authority_order_source', models.CharField(choices=[('package', 'Package'), ('default', 'Default')], editable=False, max_length=32, verbose_name='authority order source')),
                ('conda_package_snapshot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='collectors.condapackagesnapshot', verbose_name='conda package snapshot')),
                ('feedstock_snapshot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='collectors.feedstocksnapshot', verbose_name='feedstock snapshot')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='identity.package', verbose_name='package')),
                ('policy_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='core.policyrun', verbose_name='policy run')),
                ('pypi_snapshot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='collectors.pypireleasesnapshot', verbose_name='PyPI release snapshot')),
                ('source_snapshot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_findings', to='collectors.sourcereleasesnapshot', verbose_name='source release snapshot')),
            ],
            options={
                'verbose_name': 'package currency',
                'verbose_name_plural': 'package currency',
                'db_table': 'package_currency',
                'constraints': [models.UniqueConstraint(fields=('package', 'policy_run'), name='one_currency_row_per_package_per_run'), models.CheckConstraint(condition=models.Q(('chosen_authority__in', ['', 'source', 'pypi', 'feedstock', 'conda_package'])), name='currency_authority_is_a_known_surface'), models.CheckConstraint(condition=models.Q(models.Q(('chosen_authority', ''), _negated=True), models.Q(models.Q(('source_status__in', ['current', 'behind']), _negated=True), models.Q(('pypi_status__in', ['current', 'behind']), _negated=True), models.Q(('feedstock_status__in', ['current', 'behind']), _negated=True), models.Q(('conda_package_status__in', ['current', 'behind']), _negated=True)), _connector='OR'), name='currency_verdict_names_its_authority')],
            },
        ),
    ]
