# `package_python_readiness`, the derived table CPM-PY314-S03's readiness pass owns:
# one row per package per policy run, keyed (package, policy_run) exactly as
# CPM-AD-21 requires. There is no data step, because the table starts empty and a
# policy run fills it. It is emphatically **not** the health rollup and adds no
# column to it -- CPM-AD-21 says no pass writes `package_health`.
#
# Hand-edited once, and only the dependencies, on exactly the terms 0002 through
# 0005 record at length. The autodetector names each app's *newest* migration,
# which here named `core.0007` and `identity.0004` -- neither of which this table
# references. What it actually needs is `core.PolicyRun` (`core.0002_run_ledger`),
# `identity.Package` (`identity.0001_package_identity`), the two evidence tables
# this pass reads (`collectors.0010_python_readiness_assessments` and
# `collectors.0011_python_verification_results`) and this application's own
# previous migration.
#
# Every relation is PROTECT: an evidence row is the *support* for a verdict, and
# one deleted out from under a row that cites it would leave the row claiming a
# build nothing can be shown for.
#
# **The three check constraints are CPM-FR-19 made structural.** The requirement
# is that a readiness claim states which evidence type produced it, so the verdict
# and the `evidence_type` column must agree and the row must cite what it rests
# on: a verified verdict names its verification and declares `verified`, an
# inferred verdict names its assessment and declares `inferred`, and a row that
# decided nothing declares `none`. A hand-written INSERT that went round
# `policies/py314_readiness.py` entirely is refused by PostgreSQL.
#
# The fourth and fifth require the policy version and the Python series on every
# row. The series matters here more than on the two evidence tables it is copied
# from: this is the table a read surface projects, so it is the last place an
# answer about 3.14 could become indistinguishable from an answer about whatever
# comes next.

# Generated by Django 5.2.15 on 2026-09-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0010_python_readiness_assessments'),
        ('collectors', '0011_python_verification_results'),
        ('core', '0002_run_ledger'),
        ('identity', '0001_package_identity'),
        ('policies', '0005_package_remediation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePythonReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('verified_ready', 'Verified Ready'), ('verified_not_ready', 'Verified Not Ready'), ('inferred_ready', 'Inferred Ready'), ('inferred_not_ready', 'Inferred Not Ready')], editable=False, max_length=32, verbose_name='readiness')),
                ('evidence_type', models.CharField(choices=[('verified', 'Verified'), ('inferred', 'Inferred'), ('none', 'None')], editable=False, max_length=32, verbose_name='evidence type')),
                ('python_series', models.CharField(editable=False, max_length=32, verbose_name='python series')),
                ('evidence_stale', models.BooleanField(default=False, editable=False, verbose_name='evidence stale')),
                ('policy_version', models.CharField(editable=False, max_length=128, verbose_name='policy version')),
                ('evidence_cutoff', models.DateTimeField(editable=False, verbose_name='evidence cutoff')),
                ('detail', models.TextField(blank=True, default='', editable=False, verbose_name='detail')),
                ('assessment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='python_readiness_policy_findings', to='collectors.pythonreadinessassessment', verbose_name='python readiness assessment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='python_readiness_policy_findings', to='identity.package', verbose_name='package')),
                ('policy_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='python_readiness_policy_findings', to='core.policyrun', verbose_name='policy run')),
                ('verification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='python_readiness_policy_findings', to='collectors.pythonverificationresult', verbose_name='python verification result')),
            ],
            options={
                'verbose_name': 'package python readiness',
                'verbose_name_plural': 'package python readiness',
                'db_table': 'package_python_readiness',
                'constraints': [models.UniqueConstraint(fields=('package', 'policy_run'), name='one_python_readiness_row_per_package_per_run'), models.CheckConstraint(condition=models.Q(models.Q(('readiness__in', ('verified_ready', 'verified_not_ready')), _negated=True), models.Q(('evidence_type', 'verified'), ('verification__isnull', False)), _connector='OR'), name='python_readiness_verified_verdict_cites_its_build'), models.CheckConstraint(condition=models.Q(models.Q(('readiness__in', ('inferred_ready', 'inferred_not_ready')), _negated=True), models.Q(('evidence_type', 'inferred'), ('assessment__isnull', False)), _connector='OR'), name='python_readiness_inferred_verdict_cites_its_claim'), models.CheckConstraint(condition=models.Q(('readiness__in', ('verified_ready', 'verified_not_ready', 'inferred_ready', 'inferred_not_ready')), ('evidence_type', 'none'), _connector='OR'), name='python_readiness_undecided_claims_no_evidence'), models.CheckConstraint(condition=models.Q(('policy_version', ''), _negated=True), name='python_readiness_row_names_its_policy_version'), models.CheckConstraint(condition=models.Q(('python_series', ''), _negated=True), name='python_readiness_row_names_its_series')],
            },
        ),
    ]
