# `package_priority`, the derived table CPM-PRIORITY-S01's priority pass owns: one
# row per package per policy run, keyed (package, policy_run) exactly as CPM-AD-21
# requires. There is no data step, because the table starts empty and a policy run
# fills it.
#
# Hand-edited once, and only the dependencies, on exactly the terms 0002 through
# 0006 record. The autodetector named `identity.0004`, which this table does not
# reference; what it actually needs is `core.PolicyRun` (`core.0002_run_ledger`),
# `identity.Package` (`identity.0001_package_identity`), and this application's
# own previous migration. It also depends on `core.0008`, which adds the rollup
# column this pass contributes -- that one is real: `core/policy.py` refuses to
# register a pass whose contributed column is not a field on PackageHealth, so the
# column must exist before the pass does.
#
# Every relation is PROTECT, on the terms every sibling derived table states.
#
# **The first check constraint is CPM-PRIORITY-S01's AC 2 made structural.** An
# assignment explains itself: a row naming a bucket carries the bucket's
# description, the rule that matched and the reason, and a row naming no bucket
# carries none of the three. Both directions in one constraint, because "explains
# itself" is one claim and a row holding two of the three parts has not made it.
#
# **The second refuses a score of zero**, which is not fussiness about a bound. A
# score computed as though a missing usage signal were zero would land exactly
# there, and a reader would take it for "we scored this and it came out lowest" --
# about a package this product has observed nothing for. CPM-FR-20's range starts
# at 1 and an absence is NULL.
#
# There is no rank column. CPM-PRIORITY-S01's AC 1 asks that rank be *derived*
# from bucket and score and CPM-AD-1 lists it among the fields projected from the
# rollup; policies/priority.py's `ranking_order` is that derivation, and a stored
# ordinal would be a third copy that can disagree with the two columns it came
# from -- and would need a post-loop hook core/policy.py does not have.

# Generated by Django 5.2.15 on 2026-09-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_package_health_priority_status'),
        ('identity', '0001_package_identity'),
        ('policies', '0006_package_python_readiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3'), ('p4', 'P4'), ('p5', 'P5'), ('p6', 'P6'), ('p7', 'P7'), ('p8', 'P8'), ('p9', 'P9'), ('p10', 'P10')], default='unknown', editable=False, max_length=32, verbose_name='bucket')),
                ('bucket_description', models.CharField(blank=True, default='', editable=False, max_length=512, verbose_name='bucket description')),
                ('matched_rule', models.CharField(blank=True, default='', editable=False, max_length=32, verbose_name='matched rule')),
                ('reason', models.CharField(blank=True, default='', editable=False, max_length=512, verbose_name='reason')),
                ('score', models.PositiveSmallIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='score')),
                ('policy_version', models.CharField(editable=False, max_length=128, verbose_name='policy version')),
                ('evidence_cutoff', models.DateTimeField(editable=False, verbose_name='evidence cutoff')),
                ('detail', models.TextField(blank=True, default='', editable=False, verbose_name='detail')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority_policy_findings', to='identity.package', verbose_name='package')),
                ('policy_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priority_policy_findings', to='core.policyrun', verbose_name='policy run')),
            ],
            options={
                'verbose_name': 'package priority',
                'verbose_name_plural': 'package priority',
                'db_table': 'package_priority',
                'constraints': [models.UniqueConstraint(fields=('package', 'policy_run'), name='one_priority_row_per_package_per_run'), models.CheckConstraint(condition=models.Q(models.Q(('bucket__in', ('p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10')), models.Q(('bucket_description', ''), _negated=True), models.Q(('matched_rule', ''), _negated=True), models.Q(('reason', ''), _negated=True)), models.Q(models.Q(('bucket__in', ('p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10')), _negated=True), ('bucket_description', ''), ('matched_rule', ''), ('reason', '')), _connector='OR'), name='priority_bucket_explains_itself'), models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 100)), _connector='OR'), name='priority_score_in_range_or_absent'), models.CheckConstraint(condition=models.Q(('policy_version', ''), _negated=True), name='priority_row_names_its_policy_version')],
            },
        ),
    ]
