# `package_work_type`, the derived table CPM-PRIORITY-S02's work-type pass owns:
# one row per package per policy run, keyed (package, policy_run) exactly as
# CPM-AD-21 requires. There is no data step; a policy run fills it.
#
# Hand-edited once, and only the dependencies, on the terms 0002 through 0007
# record. The autodetector named `identity.0004`, which this table does not
# reference. The dependency on `core.0009` is real: core/policy.py refuses to
# register a pass whose contributed column is not a field on PackageHealth, so the
# rollup column must exist before the pass does.
#
# **The CHECK constraint is CPM-PRIORITY-S02's AC 2, and `choices` would not have
# been.** Django enforces `choices` on neither `save()` nor a migration, so a value
# outside CPM-FR-21's closed set -- a typo in a later pass, a hand-written INSERT, a
# data migration -- would reach the column unchallenged. The requirement says a
# value outside the set is *rejected*, and a rejection that only happens when
# somebody remembers to call full_clean() is not one.
#
# The four sentinels are inside the constraint as well as the eight: they are what
# the column holds for a package no work type was derived for, and for one the
# confidence gate replaced. What is refused is anything the vocabulary does not
# offer at all.
#
# There is no priority column here and no foreign key to package_priority. AC 1 is
# that the work type is computable in any bucket and that the two are not coupled,
# and a reference in this direction would be the coupling the requirement names.

# Generated by Django 5.2.15 on 2026-09-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_package_health_work_type_status'),
        ('identity', '0001_package_identity'),
        ('policies', '0007_package_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('fix_vulnerability', 'Fix Vulnerability'), ('create_recipe', 'Create Recipe'), ('file_tracking_issue', 'File Tracking Issue'), ('already_tracked', 'Already Tracked'), ('update_feedstock', 'Update Feedstock'), ('validate_python_314', 'Validate Python 314'), ('review_license', 'Review License'), ('resolve_identity', 'Resolve Identity')], default='unknown', editable=False, max_length=32, verbose_name='work type')),
                ('detail', models.TextField(blank=True, default='', editable=False, verbose_name='detail')),
                ('policy_version', models.CharField(editable=False, max_length=128, verbose_name='policy version')),
                ('evidence_cutoff', models.DateTimeField(editable=False, verbose_name='evidence cutoff')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_type_policy_findings', to='identity.package', verbose_name='package')),
                ('policy_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_type_policy_findings', to='core.policyrun', verbose_name='policy run')),
            ],
            options={
                'verbose_name': 'package work type',
                'verbose_name_plural': 'package work type',
                'db_table': 'package_work_type',
                'constraints': [models.UniqueConstraint(fields=('package', 'policy_run'), name='one_work_type_row_per_package_per_run'), models.CheckConstraint(condition=models.Q(('work_type__in', ('error', 'unknown', 'not_found', 'not_applicable', 'fix_vulnerability', 'create_recipe', 'file_tracking_issue', 'already_tracked', 'update_feedstock', 'validate_python_314', 'review_license', 'resolve_identity'))), name='work_type_is_one_of_the_closed_set'), models.CheckConstraint(condition=models.Q(('policy_version', ''), _negated=True), name='work_type_row_names_its_policy_version')],
            },
        ),
    ]
