# Generated by Django 5.2.15 on 2026-09-06 00:33
#
# `source_release_snapshots`, the table PRD Appendix A.2 names for CPM-FR-7's
# upstream release evidence (CPM-CURRENCY-S01). Hand-edited once, to narrow the
# dependency: the autodetector names identity's newest migration, and the only
# relation here is the PROTECT foreign key to `identity.Package`, which
# `0001_package_identity` creates. Depending on `0003_identity_override` would
# order this migration behind two others it does not need, which is an ordering
# constraint nobody chose and one that gets harder to unpick as the graph grows.
#
# Otherwise unedited: the model declares the whole of it -- the PROTECT relation
# EVIDENCE.02-AUDIT-001 requires of an evidence model, the read index
# core/freshness.py's query needs, and the constraint that keeps a version on
# determinate rows and both a version and a date off every other kind. There is
# no data step: the table starts empty, and nothing existing has to be repaired
# to accept it.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_inventory_snapshots'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceReleaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('latest_version', models.CharField(blank=True, default='', max_length=512, verbose_name='latest version')),
                ('released_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='released at')),
                ('last_activity_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last activity at')),
                ('releases_seen', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='releases seen')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_release_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'source release snapshot',
                'verbose_name_plural': 'source release snapshots',
                'db_table': 'source_release_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='src_release_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'ok'), models.Q(('latest_version', ''), _negated=True)), models.Q(models.Q(('state', 'ok'), _negated=True), ('latest_version', ''), ('released_at__isnull', True)), _connector='OR'), name='release_facts_present_exactly_when_observed')],
            },
        ),
    ]
