# Generated by Django 5.2.15 on 2026-09-06 01:34
#
# `pypi_release_snapshots`, the table PRD Appendix A.2 names for CPM-FR-8's PyPI
# release evidence (CPM-CURRENCY-S02). Hand-edited once, on the terms
# 0002_source_release_snapshots was: the autodetector names identity's newest
# migration, and the only relation here is the PROTECT foreign key to
# `identity.Package`, which `0001_package_identity` creates. Depending on
# `0003_identity_override` would order this migration behind two others it does
# not need.
#
# Otherwise unedited: the model declares the whole of it -- the PROTECT relation
# EVIDENCE.02-AUDIT-001 requires of an evidence model, the read index
# core/freshness.py's query needs, and the constraint that keeps a version on
# determinate rows and every fact off the sentinel rows, the `not_applicable`
# row included. There is no data step: the table starts empty.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0002_source_release_snapshots'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyPIReleaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('latest_version', models.CharField(blank=True, default='', max_length=512, verbose_name='latest version')),
                ('released_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='released at')),
                ('requires_python', models.CharField(blank=True, default='', max_length=128, verbose_name='requires python')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pypi_release_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'PyPI release snapshot',
                'verbose_name_plural': 'PyPI release snapshots',
                'db_table': 'pypi_release_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='pypi_release_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'ok'), models.Q(('latest_version', ''), _negated=True)), models.Q(models.Q(('state', 'ok'), _negated=True), ('latest_version', ''), ('released_at__isnull', True), ('requires_python', '')), _connector='OR'), name='pypi_facts_present_exactly_when_observed')],
            },
        ),
    ]
