# Generated by Django 5.2.15 on 2026-09-06 12:00
#
# `feedstock_snapshots`, the table PRD Appendix A.2 names for CPM-FR-9's
# conda-forge feedstock evidence (CPM-CURRENCY-S03). Hand-edited once, on the
# terms 0002_source_release_snapshots and 0003_pypi_release_snapshots were: the
# autodetector names identity's newest migration, and the only relation here is
# the PROTECT foreign key to `identity.Package`, which `0001_package_identity`
# creates. Depending on a later identity migration would order this one behind
# migrations it does not need.
#
# Otherwise unedited: the model declares the whole of it -- the PROTECT relation
# EVIDENCE.02-AUDIT-001 requires of an evidence model, the read index
# core/freshness.py's query needs, and the two constraints. The second of those
# is the one this table adds: a staged recipe may be recorded only on a row that
# says there is no feedstock, which is CPM-FR-9's AC 2 as a database rule rather
# than a convention. There is no data step: the table starts empty.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_pypi_release_snapshots'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedstockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('feedstock_name', models.CharField(blank=True, default='', max_length=160, verbose_name='feedstock name')),
                ('feedstock_url', models.CharField(blank=True, default='', max_length=512, verbose_name='feedstock URL')),
                ('recipe_version', models.CharField(blank=True, default='', max_length=512, verbose_name='recipe version')),
                ('recipe_build_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='recipe build number')),
                ('recipe_metadata_url', models.CharField(blank=True, default='', max_length=512, verbose_name='recipe metadata URL')),
                ('last_recipe_activity_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last recipe activity at')),
                ('staged_recipe_url', models.CharField(blank=True, default='', max_length=512, verbose_name='staged recipe URL')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedstock_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'feedstock snapshot',
                'verbose_name_plural': 'feedstock snapshots',
                'db_table': 'feedstock_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='feedstock_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'ok'), models.Q(('feedstock_name', ''), _negated=True)), models.Q(models.Q(('state', 'ok'), _negated=True), ('feedstock_name', ''), ('feedstock_url', ''), ('last_recipe_activity_at__isnull', True), ('recipe_build_number__isnull', True), ('recipe_metadata_url', ''), ('recipe_version', '')), _connector='OR'), name='feedstock_facts_present_exactly_when_observed'), models.CheckConstraint(condition=models.Q(('staged_recipe_url', ''), ('state', 'not_found'), _connector='OR'), name='staged_recipe_only_when_absent')],
            },
        ),
    ]
