# Generated by Django 5.2.15 on 2026-09-06 16:58
#
# `conda_package_snapshots`, the table PRD Appendix A.2 names for CPM-FR-10's
# published-conda-package evidence (CPM-CURRENCY-S04). Hand-edited once, on the
# terms 0002 through 0004 were: the autodetector names identity's newest
# migration, and the only relation here is the PROTECT foreign key to
# `identity.Package`, which `0001_package_identity` creates. Depending on a later
# identity migration would order this one behind migrations it does not need.
#
# Otherwise unedited: the model declares the whole of it -- the PROTECT relation
# EVIDENCE.02-AUDIT-001 requires of an evidence model, the two read indexes
# (the package-wide one core/freshness.py's query needs, and the per-(channel,
# platform) one every stated purpose of this table actually asks for), and the
# two constraints. The second of those
# is the one this table adds: every row names the channel and the platform it is
# about, sentinel rows included, which is CPM-FR-10's "channels are never merged"
# as a database rule rather than a convention. There is no data step: the table
# starts empty.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_feedstock_snapshots'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondaPackageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('channel', models.CharField(max_length=128, verbose_name='channel')),
                ('platform', models.CharField(max_length=64, verbose_name='platform')),
                ('published_version', models.CharField(blank=True, default='', max_length=512, verbose_name='published version')),
                ('build_string', models.CharField(blank=True, default='', max_length=256, verbose_name='build string')),
                ('build_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='build number')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conda_package_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'conda package snapshot',
                'verbose_name_plural': 'conda package snapshots',
                'db_table': 'conda_package_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='conda_pkg_pkg_observed'), models.Index(fields=['package', 'channel', 'platform', '-observed_at'], name='conda_pkg_pair_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'ok'), models.Q(('published_version', ''), _negated=True)), models.Q(models.Q(('state', 'ok'), _negated=True), ('build_number__isnull', True), ('build_string', ''), ('published_version', '')), _connector='OR'), name='conda_package_facts_present_exactly_when_observed'), models.CheckConstraint(condition=models.Q(models.Q(('channel', ''), _negated=True), models.Q(('platform', ''), _negated=True)), name='conda_package_names_channel_and_platform')],
            },
        ),
    ]
