# Generated by Django 5.2.15 on 2026-09-07 02:49

# `kev_findings`, the table PRD Appendix A.2 names for CPM-FR-12's KEV
# cross-reference (CPM-SECURITY-S02). Hand-edited once, on the terms 0002 through
# 0007 were: the autodetector named a later `identity` migration, and the only
# `identity` relation here is the PROTECT foreign key to `identity.Package`, which
# `0001_package_identity` creates. Depending on a later identity migration would
# order this one behind migrations it does not need.
#
# The second relation is to `collectors.VulnerabilityFinding`, which
# `0007_vulnerability_findings` creates in this same application, and it is the
# link CPM-FR-12's acceptance criterion is about: a KEV finding names the
# vulnerability finding it derives from, by foreign key rather than by a copied
# identifier. PROTECT on both, as EVIDENCE.02-AUDIT-001 requires of every relation
# on an evidence model -- Django's deletion collector bypasses every append-only
# refusal in core/models.py, so a CASCADE here would destroy a cross-reference
# when the advisory observation it derives from went.
#
# It is nullable, and the rows that leave it null are the rows that derive from no
# finding: the `unknown` one a package with nothing to cross-reference gets, and
# the `error` and `not_found` rows the base writes. An `unknown` row may also carry
# one -- a finding whose advisory identifier uses a scheme the catalog never states
# is an advisory the catalog cannot speak to, and that row is about one specific
# advisory and names it.
#
# There is no constraint pairing the link with the package, because SQL has none to
# offer: a CHECK is per row over that row's own columns, and the composite foreign
# key that would express it needs a UniqueConstraint on `vulnerability_findings`,
# which EVIDENCE.02-AUDIT-003 bans outright. `KevFinding.save` and the collector's
# own construction hold it instead; the model docstring names what that leaves.
#
# Otherwise unedited: the model declares the whole of it -- the one read index
# core/freshness.py's query needs, and the two constraints. The first makes the
# catalog facts present exactly where they are true: the link on every row derived
# from a finding and on no other, and the catalog date only on a `listed` row. The
# second refuses `not_applicable` outright, because a KEV question applies to every
# package that could have an advisory against it.
#
# **The determinate values are `listed` and `not_listed` rather than `ok`**, which
# is why `state`'s choices here are not OutcomeState's: on a security table a
# determinate row is the alarming case, and core's precedence ranks `ok` best of
# five -- collectors/outcomes.py composes the vocabulary and argues both values.
#
# There is no unique constraint of any kind (CPM-AD-2): two cross-references of one
# advisory are two rows. There is no data step: the table starts empty, and it
# stays empty until an operator declares a KEV source (docs/deployment.md).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0007_vulnerability_findings'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='KevFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('listed', 'Listed'), ('not_listed', 'Not Listed')], max_length=32, verbose_name='state')),
                ('catalog_date_added', models.DateTimeField(blank=True, default=None, null=True, verbose_name='catalog date added')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kev_findings', to='identity.package', verbose_name='package')),
                ('vulnerability_finding', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kev_findings', to='collectors.vulnerabilityfinding', verbose_name='vulnerability finding')),
            ],
            options={
                'verbose_name': 'KEV finding',
                'verbose_name_plural': 'KEV findings',
                'db_table': 'kev_findings',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='kev_finding_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'listed'), ('vulnerability_finding__isnull', False)), models.Q(('state', 'not_listed'), ('catalog_date_added__isnull', True), ('vulnerability_finding__isnull', False)), models.Q(('state', 'unknown'), ('catalog_date_added__isnull', True)), models.Q(models.Q(('state', 'listed'), _negated=True), models.Q(('state', 'not_listed'), _negated=True), models.Q(('state', 'unknown'), _negated=True), ('catalog_date_added__isnull', True), ('vulnerability_finding__isnull', True)), _connector='OR'), name='kev_facts_present_exactly_when_cross_referenced'), models.CheckConstraint(condition=models.Q(('state', 'not_applicable'), _negated=True), name='kev_applies_to_every_package')],
            },
        ),
    ]
