# Generated by Django 5.2.15 on 2026-09-07 04:51

# `license_findings`, the table PRD Appendix A.2 names for CPM-FR-13's licence
# evidence (CPM-SECURITY-S03). Hand-edited once, on the terms 0002 through 0008
# were: the autodetector named a later `identity` migration, and the only
# `identity` relation here is the PROTECT foreign key to `identity.Package`, which
# `0001_package_identity` creates. Depending on a later identity migration would
# order this one behind migrations it does not need.
#
# PROTECT, as EVIDENCE.02-AUDIT-001 requires of every relation on an evidence
# model -- Django's deletion collector bypasses every append-only refusal in
# core/models.py, so a CASCADE here would destroy a package's licence history when
# the package went.
#
# Otherwise unedited: the model declares the whole of it -- the one read index
# core/freshness.py's query needs, and the three constraints.
#
# **The first constraint is deliberately asymmetric, and that is CPM-FR-13's AC 1
# in the schema.** It requires the normalized expression and the detection method
# on a `normalized` row and forbids them on every other one, and it says nothing
# whatever about `raw_license` -- which is permitted on every row there is. A row
# that failed to normalize must be able to carry the raw string the channel
# stated: that is what makes it a review item somebody can act on rather than an
# absence of information, and a constraint that tidied it away would delete the
# evidence AC 1 exists to record.
#
# The second refuses `not_applicable` outright, because every package a monitored
# channel could serve is licensed under something. The third requires the channel
# on every row, sentinel rows included, because two channels stating different
# licences are two facts and a row that could not say which channel it came from
# would have merged them.
#
# **The determinate value is `normalized` rather than `ok`**, which is why
# `state`'s choices here are not OutcomeState's: on a licence table `ok` reads as
# "this licence is fine", which is a compliance verdict CPM-SECURITY-S03's AC 2
# forbids this collector from making and which CPM-FR-18 gives to a policy that
# does not exist yet -- collectors/outcomes.py composes the vocabulary and argues
# it. There is no policy-result column of any kind: a collector may not compute a
# derived status (CPM-AD-8) and a policy pass writes only its own derived table
# (CPM-AD-21), so PRD Appendix A.2's policy result is recorded as not-taken in that
# story's Spec Change Log rather than smuggled onto an evidence row.
#
# There is no unique constraint of any kind (CPM-AD-2): two observations of one
# package's licence on one channel are two rows. There is no data step: the table
# starts empty, and it stays empty until an operator declares CPM_MONITORED_CHANNELS
# (docs/conda-sentinel/operations.md).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0008_kev_findings'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('normalized', 'Normalized')], max_length=32, verbose_name='state')),
                ('channel', models.CharField(max_length=128, verbose_name='channel')),
                ('raw_license', models.CharField(blank=True, default='', max_length=512, verbose_name='raw license')),
                ('normalized_license', models.CharField(blank=True, default='', max_length=2048, verbose_name='normalized license')),
                ('detection_method', models.CharField(blank=True, choices=[('spdx-identifier', 'Spdx Identifier'), ('recognised-spelling', 'Recognised Spelling'), ('spdx-expression', 'Spdx Expression')], default='', max_length=32, verbose_name='detection method')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_findings', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'license finding',
                'verbose_name_plural': 'license findings',
                'db_table': 'license_findings',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='license_finding_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'normalized'), models.Q(('normalized_license', ''), _negated=True), models.Q(('detection_method', ''), _negated=True)), models.Q(models.Q(('state', 'normalized'), _negated=True), ('detection_method', ''), ('normalized_license', '')), _connector='OR'), name='license_facts_present_exactly_when_normalized'), models.CheckConstraint(condition=models.Q(('state', 'not_applicable'), _negated=True), name='license_applies_to_every_package'), models.CheckConstraint(condition=models.Q(('channel', ''), _negated=True), name='license_names_the_channel_it_is_about')],
            },
        ),
    ]
