# Generated by Django 5.2.15 on 2026-09-08 02:35

# `python_readiness_assessments`, CPM-PY314-S01's static half of CPM-FR-14.
# Hand-edited once, on the terms 0002 through 0009 were: the autodetector named a
# later `identity` migration, and the only `identity` relation here is the PROTECT
# foreign key to `identity.Package`, which `0001_package_identity` creates.
# Depending on a later identity migration would order this one behind migrations it
# does not need.
#
# PROTECT, as EVIDENCE.02-AUDIT-001 requires of every relation on an evidence model
# -- Django's deletion collector bypasses every append-only refusal in
# core/models.py, so a CASCADE here would destroy a package's readiness history when
# the package went.
#
# Otherwise unedited: the model declares the whole of it -- the one read index
# core/freshness.py's query needs, and the three constraints.
#
# **The determinate values name the inference**, which is why `state`'s choices here
# are neither OutcomeState's nor a bare `compatible`/`incompatible` pair. CPM-FR-14
# requires inferred and *verified* compatibility to be distinct recorded states and
# CPM-AD-24 carries a state's value verbatim onto every read surface, so a value
# called `compatible` on this table would sit on a queue beside CPM-PY314-S02's
# verified result and read identically. collectors/outcomes.py composes the
# vocabulary and argues it.
#
# **There is no determinate value for a silence, and that is the whole story.** A
# project that declared nothing about this Python records `unknown` -- the sentinel
# core already has for "nothing was established". Most projects have not declared
# 3.14 support, so a value that read a silence as a claim would report most of an
# inventory as incompatible on no evidence.
#
# The first constraint is the biconditional over the one column that is a judgement
# rather than a transcription: the deciding signal is present exactly on an inferred
# row. `requires_python` and `matching_classifier` appear in neither half on purpose
# -- they are what the source stated, and an `unknown` row carrying them is the
# review item this table exists to leave behind.
#
# The second is the **opposite** of the three security tables' applicability rule,
# and it is the one place this table differs from all of them. They refuse
# `not_applicable` outright; CPM-PY314-S01 AC 2 asks for it, because a package with
# no release ecosystem has no Python metadata to assess. What is refused instead is a
# `not_applicable` row with no reason: the only thing that can establish the state is
# identity's own `not_applicable` mapping, and a row that could not name it would be
# indistinguishable from one written out of an *absence* of identity -- which is
# exactly what this story forbids.
#
# The third requires the assessed Python series on every row, sentinel rows included,
# because CPM-PY314-S02 writes a verified result about a series and CPM-PY314-S03
# reduces both.
#
# There is no unique constraint of any kind (CPM-AD-2): a project that declares 3.14
# support later is a new row and the old one stands, which is how a reader sees
# *when* a project became ready. There is no derived status and no readiness verdict:
# a collector may not compute one (CPM-AD-8) and a policy pass writes only its own
# derived table (CPM-AD-21), so CPM-FR-19's readiness is CPM-PY314-S03's. There is no
# data step: the table starts empty.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0009_license_findings'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonReadinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('inferred_compatible', 'Inferred Compatible'), ('inferred_incompatible', 'Inferred Incompatible')], max_length=32, verbose_name='state')),
                ('python_series', models.CharField(max_length=32, verbose_name='python series')),
                ('requires_python', models.CharField(blank=True, default='', max_length=128, verbose_name='requires python')),
                ('matching_classifier', models.CharField(blank=True, default='', max_length=256, verbose_name='matching classifier')),
                ('deciding_signal', models.CharField(blank=True, choices=[('requires-python', 'Requires-Python'), ('classifier', 'Classifier'), ('both', 'Both')], default='', max_length=32, verbose_name='deciding signal')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='python_readiness_assessments', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'python readiness assessment',
                'verbose_name_plural': 'python readiness assessments',
                'db_table': 'python_readiness_assessments',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='py_readiness_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state__in', ('inferred_compatible', 'inferred_incompatible')), models.Q(('deciding_signal', ''), _negated=True)), models.Q(models.Q(('state__in', ('inferred_compatible', 'inferred_incompatible')), _negated=True), ('deciding_signal', '')), _connector='OR'), name='readiness_signal_present_exactly_when_inferred'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'not_applicable'), _negated=True), models.Q(('detail', ''), _negated=True), _connector='OR'), name='readiness_not_applicable_states_its_reason'), models.CheckConstraint(condition=models.Q(('python_series', ''), _negated=True), name='readiness_names_the_series_it_assessed')],
            },
        ),
    ]
