# Generated by Django 5.2.15 on 2026-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_provision_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='finished at')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16, verbose_name='status')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('collector', models.CharField(max_length=128, verbose_name='collector')),
                ('package_id', models.PositiveBigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='package id')),
            ],
            options={
                'verbose_name': 'collection run',
                'verbose_name_plural': 'collection runs',
                'db_table': 'collection_runs',
            },
        ),
        migrations.CreateModel(
            name='PolicyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='finished at')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=16, verbose_name='status')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('policy_version', models.CharField(max_length=128, verbose_name='policy version')),
                ('evidence_cutoff', models.DateTimeField(verbose_name='evidence cutoff')),
            ],
            options={
                'verbose_name': 'policy run',
                'verbose_name_plural': 'policy runs',
                'db_table': 'policy_runs',
            },
        ),
    ]
