# Generated by Django 5.2.15 on 2026-09-06 20:37
#
# `currency_status`, the first domain status column on `package_health`
# (CPM-CURRENCY-S06). `epics.md` says the rollup "grows as passes are added", and
# this is the first pass -- the column and the pass that produces it land in one
# story, so no deployment ever holds a column nothing writes.
#
# Unedited. The six choices are frozen here as literals, exactly as the state
# vocabularies in the collectors' migrations are: a migration records what the
# schema was asked to be, and one that followed
# `policies/outcomes.py`'s composed type would silently rewrite history the day a
# seventh verdict is added.
#
# The `default` is `unknown` and it is load-bearing rather than cosmetic: every
# existing rollup row acquires it, and `unknown` is what is true of a package no
# currency pass had run against. A default of `ok` would have made every row in
# an existing deployment read clean at `migrate` time.
#
# There is no data step and none is owed: `core/rollup.py` replaces every column
# of every row on each run, so the next policy run overwrites the default with a
# computed verdict.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grant_identity_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehealth',
            name='currency_status',
            field=models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('current', 'Current'), ('behind', 'Behind')], default='unknown', editable=False, max_length=32, verbose_name='currency'),
        ),
    ]
