# `package_health.priority_status`, the rollup's third domain status column
# (CPM-AD-11), added by CPM-PRIORITY-S01 in the same story as the PriorityPass
# that produces it, on exactly the terms 0007 records: a column added ahead of its pass is one nothing writes and one
# every read surface reports `unknown` for forever.
#
# The default is `unknown` and is frozen here as the string. Every existing row
# acquires it, and core/rollup.py puts that default through CPM-AD-4's gate on
# every compose exactly as it does a contributed verdict.
#
# **`p10` as a default would have been the mistake this column is most exposed
# to.** It is the bucket that looks harmless -- "lowest priority" reads as a
# considered answer rather than as an absence -- so every package this product
# had never prioritised would have arrived in the queue as one somebody had
# decided was unimportant. `unknown` is the honest default and is the value the
# confidence gate already writes.
#
# The choices are frozen as the fourteen PriorityBucket offers on the day this
# ran: the four sentinels core/outcomes.py composes in, plus p1 through p10.
# Django enforces `choices` on neither `save()` nor a migration, so this records
# what the schema was asked to be rather than a rule the database keeps.

# Generated by Django 5.2.15 on 2026-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_package_health_feedstock_presence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehealth',
            name='priority_status',
            field=models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3'), ('p4', 'P4'), ('p5', 'P5'), ('p6', 'P6'), ('p7', 'P7'), ('p8', 'P8'), ('p9', 'P9'), ('p10', 'P10')], default='unknown', editable=False, max_length=32, verbose_name='priority'),
        ),
    ]
