# `package_health.work_type_status`, the rollup's fourth domain status column
# (CPM-AD-11), added by CPM-PRIORITY-S02 in the same story as the WorkTypePass
# that produces it, on exactly the terms 0007 and 0008 record.
#
# The default is `unknown` and is frozen here as the string. Every existing row
# acquires it, and core/rollup.py puts that default through CPM-AD-4's gate on
# every compose exactly as it does a contributed verdict.
#
# **This column sits beside priority_status and is not derived from it**, which is
# CPM-PRIORITY-S02's AC 1. The adjacency on one row is the whole hazard the
# requirement is written about: a low-priority package still has a recommended
# action, and a read surface that inferred one column from the other would lose
# exactly that. policies/work_type.py reads neither the bucket nor the priority
# table, and its pass is registered before the priority pass so it could not.
#
# The choices are frozen as the twelve WorkType offers on the day this ran: the
# four sentinels core/outcomes.py composes in, plus CPM-FR-21's closed set of
# eight from PRD Appendix A.1. Django enforces `choices` on neither `save()` nor a
# migration, which is why package_work_type carries a CHECK constraint over the
# same set -- AC 2 asks for a rejection, and this records only what the schema was
# asked to be.

# Generated by Django 5.2.15 on 2026-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_package_health_priority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehealth',
            name='work_type_status',
            field=models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('fix_vulnerability', 'Fix Vulnerability'), ('create_recipe', 'Create Recipe'), ('file_tracking_issue', 'File Tracking Issue'), ('already_tracked', 'Already Tracked'), ('update_feedstock', 'Update Feedstock'), ('validate_python_314', 'Validate Python 314'), ('review_license', 'Review License'), ('resolve_identity', 'Resolve Identity')], default='unknown', editable=False, max_length=32, verbose_name='work type'),
        ),
    ]
