# `background_jobs`, the table a request points at after handing work off
# (CPM-AD-9, CPM-APP-S08). The one table in this application that is not
# append-only, and the model docstring says why: a job is not evidence about
# anything, it is a piece of work with a lifecycle, and a second row per state
# change would make "is this done" a query rather than a read.
#
# Two check constraints, and both refuse a row that would make a status page lie.
# `job_finish_stamp_matches_its_state` refuses a finished job with no finish stamp
# and an unfinished one that has one -- the failure being a page that says
# "running" about work that ended an hour ago, which is indistinguishable from
# work that hung. `a_failed_job_says_why` refuses a failure with no explanation,
# which is the report an operator can do nothing with.
#
# `artifact` is a TextField rather than a FileField, and that is a v1 decision
# with a reason: production's STORAGES names FileSystemStorage, so a worker
# writing to its own container's disk produces a file the web replica serving the
# download cannot see. Object storage would fix it and is not configured. A later
# story that configures it moves this column and nothing else.
#
# `requested_by` is SET_NULL so a job survives the account that requested it --
# the record of what ran is not the record of who is still employed.

# Generated by Django 5.2.15 on 2026-09-10 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_package_health_work_type_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=64, verbose_name="kind")),
                ("parameters", models.JSONField(blank=True, default=dict, verbose_name="parameters")),
                ("state", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=9, verbose_name="state")),
                ("requested_at", models.DateTimeField(verbose_name="requested at")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="finished at")),
                ("artifact", models.TextField(blank=True, verbose_name="artifact")),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="row count")),
                ("detail", models.TextField(blank=True, verbose_name="detail")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="background_jobs", to=settings.AUTH_USER_MODEL, verbose_name="requested by")),
            ],
            options={
                "verbose_name": "background job",
                "verbose_name_plural": "background jobs",
                "db_table": "background_jobs",
                "ordering": ("-requested_at", "-id"),
                "indexes": [models.Index(fields=["requested_by", "-requested_at"], name="background_jobs_by_requester")],
                "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("finished_at__isnull", True), ("state__in", ("queued", "running"))), models.Q(("finished_at__isnull", False), ("state__in", ("succeeded", "failed"))), _connector="OR"), name="job_finish_stamp_matches_its_state"), models.CheckConstraint(condition=models.Q(models.Q(("detail__gt", ""), ("state", "failed")), models.Q(models.Q(("state", "failed"), _negated=True), ("detail", "")), _connector="OR"), name="a_failed_job_says_why")],
            },
        ),
    ]
