# Generated by Django 5.2.15 on 2026-09-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_run_ledger'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(verbose_name='computed at')),
                ('evidence_cutoff', models.DateTimeField(verbose_name='evidence cutoff')),
                ('confidence', models.CharField(choices=[('verified', 'Verified'), ('inventory-derived', 'Inventory Derived'), ('unmapped', 'Unmapped')], max_length=32, verbose_name='confidence')),
                ('policy_versions', models.JSONField(blank=True, default=dict, verbose_name='policy versions')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='health', to='identity.package', verbose_name='package')),
                ('policy_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollup_rows', to='core.policyrun', verbose_name='policy run')),
            ],
            options={
                'verbose_name': 'package health',
                'verbose_name_plural': 'package health',
                'db_table': 'package_health',
                'indexes': [models.Index(fields=['evidence_cutoff'], name='package_health_cutoff'), models.Index(fields=['computed_at'], name='package_health_computed')],
            },
        ),
    ]
